### ISSUE TITLE
Attempt to get library building without the Rust standard library

### ISSUE THREAD

**Issue by ernieturner** [IronCoreLabs/recrypt-rs#88]
We should see how much work it would take to try and get recrypt to compile without the Rust standard library. This would make it much more portable and let it work in environments such as Alpine linux. Probably a feature flag and not something we'd do by default. This ticket will just be the investigation work and we'll write up subsequent tickets on things to change if the investigation goes well.

**Comment by skeet70** [comment]
I built gridiron `no_std` successfully in [no_std](https://github.com/IronCoreLabs/gridiron/tree/no_std) and [no_std_flag](https://github.com/IronCoreLabs/gridiron/tree/no_std_flag). Benchmarking showed some (2-5%) change but repeated benchmarks seemed to vary so that may not have been a real issue.

Moving to recrypt revealed that the [`Error` type requires std](https://github.com/rust-lang/rfcs/issues/2262) as do [alternatives](https://github.com/rust-lang-nursery/failure/issues/205). This means `quick_error` can't be no_std, and we're using that a lot. The rust standard library `Mutex` also requires std, though there are [alternative](https://github.com/Amanieu/parking_lot) [implementations](https://github.com/mvdnes/spin-rs) that seem to be quality. Both of these problems are pretty large effort to get past so I'm going to stop working on this for now, but if we decide we want to do the work it should be possible.
